server:
  port: 8080

spring:
  application:
    name: file-downloader

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_PASSWORD:admin123}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

file-downloader:
  download-directory: ${FILE_DOWNLOAD_DIR:./downloads}
  thread-pool:
    core-size: 5
    max-size: 20
    queue-capacity: 100
    keep-alive-seconds: 60
  download:
    timeout-seconds: 300
    max-file-size-mb: 500
    chunk-size-kb: 8192
    parallel-chunk-size-mb: 10
    parallel-threshold-mb: 50

logging:
  level:
    com.example.filedownloader: DEBUG
    org.springframework.amqp: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"